// Every user-visible string in the app, in one place.
// Plain strings, or small functions for text with values in it.
// (Exceptions that must exist before JS runs: <title>/meta description in index.html
// and name/description in manifest.webmanifest.)

export const STRINGS = Object.freeze({
  app: {
    name: 'runsesh',
    logoAlt: 'runsesh',
    navLabel: 'Main',
    tabRace: 'Race',
    tabCompetition: 'Competition',
    tabProfile: 'Profile',
    back: 'Back',
    genericError: 'Something went wrong. Please try again.',
    updateAvailable: 'An update is available.',
    updateReload: 'Reload',
  },

  common: {
    notConnectedTitle: 'Not connected yet',
    notConnectedDefault: 'This screen shows mock data. Nothing is saved to an account.',
    comingLater: 'Coming later',
    rank: (n) => `Rank ${n}`,
    ordinal: (n) => {
      const mod100 = n % 100;
      const suffix = mod100 >= 11 && mod100 <= 13 ? 'th' : ({ 1: 'st', 2: 'nd', 3: 'rd' }[n % 10] || 'th');
      return `${n}${suffix}`;
    },
    steps: (n) => `${n} steps`,
  },

  installHint: {
    before: 'Install runsesh: tap ',
    share: 'Share',
    middle: ', then ',
    addToHome: 'Add to Home Screen',
    after: '.',
    why: 'It opens full screen like an app.',
    howTo: 'How to install',
    dismiss: 'Dismiss',
  },

  // iPhone / iPad set-up screen (#/profile/iphone)
  iphone: {
    title: 'runsesh on iPhone',
    statusTitle: 'This device',
    statusInstalled: 'Installed: you are using the runsesh app from your Home Screen.',
    statusBrowser: 'Not installed yet: you are using runsesh in the browser.',
    statusOther: 'This is not an iPhone or iPad. These steps are for Apple devices.',
    installTitle: 'Install from Safari',
    installSteps: [
      'Open runsesh in Safari (on iOS 16.4 or later other browsers work too).',
      'Tap the Share button (the square with an arrow pointing up).',
      'Scroll down and tap "Add to Home Screen", then tap "Add".',
      'Open runsesh from the new icon on your Home Screen.',
    ],
    loginTitle: 'Log in once more',
    loginText: 'The installed app keeps its own login, separate from Safari. Log in again inside the app. Password reset links always open in Safari, so finish a reset there, then log in inside the app.',
    stepsTitle: 'Your steps from Apple Health',
    stepsText: 'A web app cannot read Apple Health. An Apple Shortcut on your iPhone reads your daily step total and sends it to runsesh. Set it up below, or enter your steps by hand.',
    manualAction: 'Enter steps by hand',
    // Shortcut key
    keyTitle: 'Your Shortcut key',
    keyIntro: 'The Shortcut uses a personal key instead of your password. The key can only send your own daily steps; it cannot read anything or log in.',
    keyNone: 'You have no Shortcut key yet.',
    keyStatus: (hint, created) => `Active key ending in …${hint}, created ${created}.`,
    keyLastUsed: (when) => `Last used ${when}.`,
    keyNeverUsed: 'Not used yet.',
    keyCreate: 'Create Shortcut key',
    keyReplace: 'Replace key',
    keyRevoke: 'Revoke key',
    keyReplaceConfirm: 'Replace your key? Your Shortcut stops working until you paste the new key into it.',
    keyRevokeConfirm: 'Revoke your key? Your Shortcut stops sending steps.',
    keyShownOnce: 'Copy this key now and paste it into your Shortcut. It is shown only once; runsesh does not keep it. Do not share it.',
    keyCopy: 'Copy key',
    keyCopied: 'Key copied.',
    keyCopyFailed: 'Could not copy. Select the key and copy it by hand.',
    keyHide: 'Done',
    keyFailed: 'Could not reach the server. Try again in a moment.',
    keyRevoked: 'Key revoked.',
    keyLoading: 'Loading…',
    // Building the Shortcut
    buildTitle: 'Build the Shortcut',
    buildSteps: [
      'Open the Shortcuts app, tap +, and name the shortcut "runsesh steps".',
      'Add "Find Health Samples": type Steps, Start Date is Today. Add the filter Source is your iPhone (or only your Apple Watch), so steps are not counted twice.',
      'Add "Calculate Statistics": Sum of the Health Samples. Then add "Round Number" to the Ones Place.',
      'Add "Format Date": Current Date, Custom format yyyy-MM-dd.',
      'Add "Get Contents of URL" with the address below. Method POST. Header Authorization = Bearer followed by a space and your key. Request Body JSON: day (Text) = Formatted Date, steps (Number) = Rounded Number.',
      'Run it once and allow access to Health. Your steps appear in Health connect.',
      'Automate it: Automation → + → Time of Day (for example 21:00, Daily) → Run Immediately → Run Shortcut "runsesh steps".',
    ],
    urlLabel: 'Address for "Get Contents of URL"',
    copyUrl: 'Copy address',
    urlCopied: 'Address copied.',
    limitsNote: 'Up to 30 sends per hour. Only today and the last 3 days can be sent.',
    updateTitle: 'Updates',
    updateText: 'When a new version is ready you will see "An update is available". Tap Reload. If nothing changes, close the app completely and open it again.',
  },

  race: {
    createParty: 'Create a party',
    partyMembers: (party) => `${party} members`,
    trackLabel: "Today's race track. Swipe sideways to travel along it.",
    trackStart: 'Start',
    trackTick: (k) => `${k}k`,
    runnerLabel: (name, steps) => `${name}: ${steps} steps today`,
    minimapLabel: 'Overview of all runners. Tap a runner to jump to them.',
    you: 'You',
    todayTitle: 'Rankings',
    yourSteps: 'Your steps today',
    mockOthers: 'Your steps are real. The other runners are demo data until parties arrive.',
    leader: 'Leading today',
    behind: (steps, name) => `${steps} behind ${name}`,
    tied: (name) => `Tied with ${name}`,
  },

  competition: {
    banner: 'COMPETITION',
    screenTitle: 'Competition settings',
    hubTitle: 'Competition',
    standingsTitle: 'Standings',
    settingsButton: 'Competition settings',
    themeTitle: 'Competition theme',
    themeHint: 'Changes how this competition looks. Stored on this device only for now.',
    themeSaved: (name) => `Theme: ${name}`,
    themes: {
      circus: 'Classic circus',
      spring: 'Spring',
      summer: 'Summer',
      fall: 'Fall (spooky)',
      winter: 'Winter',
    },
    notConnected: 'Competitions are stored on this device only, with mock steps.',
    none: 'No competition yet.',
    create: 'Create a competition',
    mockRulesHint: 'Mock rules for now: per-day modes score finished days only.',
    datesRange: (start, end) => `${start} – ${end}`,
    datesOpen: (start) => `From ${start} (no end date)`,
    statusRunning: 'Running',
    statusNotStarted: 'Not started',
    statusFinished: 'Finished',
    goldenReward: 'Golden reward',
    scoreDaysWon: (n) => `${n} ${n === 1 ? 'day' : 'days'} won`,
    scorePoints: (n) => `${n} pts`,
    scoreSteps: (n) => `${n} steps`,
    showCompetition: 'Show competition',
    pickerLabel: 'Competition',
    mockSuffix: (name) => `${name} (mock)`,
    modes: {
      days_won: 'Days won',
      points_321: 'Points 3-2-1',
      total_steps: 'Total steps',
    },
    form: {
      name: 'Name (optional)',
      namePlaceholder: 'e.g. Autumn Sprint',
      start: 'Start date',
      end: 'End date (optional)',
      endHint: 'Leave empty for an open-ended competition.',
      mode: 'Ranking mode',
      golden: 'Golden reward for the winner',
      submit: 'Create competition',
      created: 'Competition created (local mock only).',
      defaultName: 'Competition',
    },
    errors: {
      nameTooLong: (max) => `Use at most ${max} characters.`,
      startMissing: 'Pick a start date.',
      endInvalid: 'That end date is not valid.',
      endBeforeStart: 'The end date must be on or after the start date.',
      modeMissing: 'Pick a ranking mode.',
      invalid: 'Invalid value.',
      tooMany: (max) => `You can keep up to ${max} local competitions.`,
    },
  },

  profile: {
    customize: 'Customize your avatar',
    yourAvatar: 'Your avatar',
    tapToCustomize: 'Tap to customize',
    customizeButton: 'Customize avatar',
    noName: 'Runner',
    uploadPhoto: 'Use your own photo as profile picture',
    photoLater: 'Custom profile photos are coming in a later phase.',
    darkTheme: 'Dark theme',
    groupParty: 'PARTY',
    groupSettings: 'SETTINGS',
    partySettings: 'Party settings',
    manageMembers: 'Manage members',
    partyRules: 'Party rules',
    competition: 'Competition',
    login: 'Login / Log out',
    account: 'Account',
    health: 'Health connect',
  },

  avatarEditor: {
    title: 'Your avatar',
    preview: 'Avatar preview',
    skin: 'Skin / body color',
    skinPicker: 'Pick any color',
    swatch: (hex) => `Color ${hex}`,
    tabs: {
      skin: 'Body color',
      hair: 'Hair',
      hairColor: 'Hair color',
      top: 'Tops',
      bottom: 'Bottoms',
      shoes: 'Shoes',
      acc: 'Accessories',
    },
    goldenTitle: 'Golden set',
    goldenHint: 'Locked. Win competitions with a golden reward to unlock.',
    locked: (label) => `${label} (locked)`,
    save: 'Save avatar',
    saved: 'Avatar saved.',
    saveFailed: 'Could not save that avatar.',
  },

  // Labels for avatar part IDs (see js/avatar/parts.js and docs/avatar-schema.md).
  parts: {
    h_none: 'Bald', h_buzz: 'Buzz', h_short: 'Short', h_spiky: 'Spiky', h_long: 'Long',
    h_bob: 'Bob', h_ponytail: 'Ponytail', h_bun: 'Bun', h_curly: 'Curly', h_mohawk: 'Mohawk',
    hc_black: 'Black', hc_brown: 'Brown', hc_auburn: 'Auburn', hc_blonde: 'Blonde',
    hc_grey: 'Grey', hc_blue: 'Blue', hc_pink: 'Pink', hc_green: 'Green',
    t_tee: 'T-shirt', t_tank: 'Tank top', t_jersey: 'Knit sweater', t_hoodie: 'Hoodie',
    t_jacket: 'Jacket', t_singlet: 'Race singlet', t_tracksuit: 'Tracksuit',
    b_shorts: 'Shorts', b_runshorts: 'Running shorts', b_leggings: 'Leggings',
    b_joggers: 'Joggers', b_skirt: 'Skirt',
    s_none: 'Barefoot', s_runner: 'Green runners', s_white: 'White trainers',
    s_blue: 'Blue runners', s_pink: 'Pink runners',
    a_none: 'None', a_cap: 'Cap', a_headband: 'Headband', a_sunglasses: 'Sunglasses',
    a_glasses: 'Glasses', a_headphones: 'Headphones', a_scarf: 'Scarf', a_medal: 'Medal',
    a_watch: 'Sports watch',
    g_glasses: 'Golden glasses', g_vest: 'Golden vest', g_boots: 'Golden boots',
    g_crown: 'Golden crown', g_color: 'Golden color',
  },

  createParty: {
    title: 'Create a party',
    notConnected: 'Parties and invites arrive in a later phase.',
    cardTitle: 'New party',
    name: 'Party name',
    namePlaceholder: 'e.g. Lunch Break Runners',
    invite: 'Invite by email',
    invitePlaceholder: 'friend@example.com',
    submit: 'Create party',
  },

  members: {
    title: 'Manage members',
    admin: (name) => `${name} (admin)`,
    remove: 'Remove',
    invite: 'Invite members',
  },

  rules: {
    title: 'Party rules',
    cardTitle: 'Rules',
    dayResets: 'Day resets at',
    joining: 'Joining',
    inviteOnly: 'Invite only',
    open: 'Open',
    edit: 'Edit rules',
    scoringTitle: 'Step scoring',
    scoringHint: 'Mock setting. It does not change rankings yet. Elevation data is not available from Health Connect or the web app, so the bonus is coming later.',
    scoring: {
      plain: 'Plain steps',
      elevation_bonus: 'Bonus for steps with elevation gain (coming later)',
    },
    scoringSaved: 'Step scoring updated (local mock only).',
  },

  login: {
    title: 'Login / Log out',
    signedInAs: (email) => `Signed in as ${email}`,
    logOut: 'Log out',
    logOutAll: 'Log out of all devices',
    logOutAllHint: 'Ends your session on every phone and computer.',
  },

  // Sign-up, login, password reset. Messages never reveal whether an email has an account.
  auth: {
    notConfigured: 'runsesh is not connected to its server yet. (Developer: fill in js/config.js.)',
    tagline: 'Step competitions with your party.',
    loginTitle: 'Log in',
    signupTitle: 'Create an account',
    forgotTitle: 'Forgot password',
    resetTitle: 'Set a new password',
    email: 'Email',
    password: 'Password',
    newPassword: 'New password',
    displayName: 'Display name',
    displayNameHint: '2 to 30 characters. Your party sees this name.',
    passwordHint: (min) => `At least ${min} characters. Long passphrases are great; password managers welcome.`,
    logIn: 'Log in',
    signUp: 'Create account',
    sendReset: 'Send reset link',
    savePassword: 'Save new password',
    toSignup: 'New here? Create an account',
    toLogin: 'Already have an account? Log in',
    toForgot: 'Forgot your password?',
    privacyLink: 'Privacy policy',
    privacyAgree: 'By creating an account you agree to the privacy policy.',
    working: 'Please wait…',
    // Generic results
    loginFailed: 'Could not log in. Check your email and password, and make sure you confirmed your email.',
    signupDone: 'Check your email. If you can create an account with this address, we sent you a confirmation link. After confirming, return to the app and log in.',
    signupFailed: 'Could not create the account. Check your details and try again in a moment.',
    resetSent: 'If an account exists for this email, we have sent a link to reset your password.',
    resetDone: 'Your password was changed. Other devices were logged out.',
    resetFailed: 'Could not change the password. The link may have expired; request a new one.',
    resetNeedsLink: 'Open the reset link from your email to set a new password.',
    // Field errors
    emailInvalid: 'Enter a valid email address.',
    passwordShort: (min) => `Use at least ${min} characters.`,
    passwordLong: 'That password is too long (max 72 bytes).',
    nameInvalid: 'Use 2 to 30 characters.',
  },

  // auth-callback.html (opened from email links, usually in the phone's browser)
  callback: {
    working: 'Checking your link…',
    confirmed: 'Email confirmed. After confirming, return to the app and log in.',
    confirmedElsewhere: 'If this was a sign-up link, your email is confirmed: return to the app and log in. If it was a password reset, open the link in the same browser where you asked for it, or request a new one.',
    invalid: 'This link is invalid or has expired. Request a new one from the app.',
    openApp: 'Open runsesh',
  },

  account: {
    title: 'Account',
    cardTitle: 'Your account',
    name: 'Display name',
    email: 'Email',
    noName: 'Not set yet',
    editName: 'Change display name',
    saveName: 'Save name',
    nameSaved: 'Display name saved.',
    nameFailed: 'Could not save the name. Use 2 to 30 characters.',
    changePassword: 'Change password',
    savePassword: 'Save new password',
    passwordChanged: 'Password changed. Other devices were logged out.',
    passwordFailed: 'Could not change the password. Try again.',
    sessionTitle: 'Sessions',
    dangerZone: 'Delete account',
    deleteAccount: 'Delete account and data',
    deleteLater: 'Account deletion is coming soon. Until then, ask us through the contact in the privacy policy.',
    privacyLink: 'Privacy policy',
  },

  health: {
    title: 'Health connect',
    intro: 'Ways to send your daily steps to runsesh:',
    androidTitle: 'Android: runsesh app',
    androidText: 'The runsesh Android app reads your daily step total from Health Connect. A browser cannot read Health Connect, so the app is required.',
    androidAction: 'About the Android app',
    androidSectionTitle: 'Android app',
    androidSection: 'The Android app is coming soon. Until then, use manual entry.',
    shortcutTitle: 'iPhone: Apple Shortcut',
    shortcutText: 'An Apple Shortcut reads your daily step total from Apple Health and sends it to runsesh.',
    shortcutAction: 'Set up on iPhone',
    manualTitle: 'Manual entry',
    manualText: "Type in today's step total.",
    manualLabel: "Today's steps",
    manualSave: 'Save steps',
    manualSaved: 'Steps saved.',
    manualInvalid: 'Enter a whole number from 0 to 100,000.',
    manualFailed: 'Could not save your steps. Try again.',
    historyTitle: 'Your last 7 days',
    historyEmpty: 'No steps saved yet.',
    historyFailed: 'Could not load your history.',
    sources: { manual: 'manual', health_connect: 'Health Connect', shortcut: 'Shortcut' },
    privacy: 'Only daily step totals are saved. Steps are self-reported.',
    privacyLink: 'Privacy policy',
  },
});
