// Every user-visible string in the app, in one place.
// Plain strings, or small functions for text with values in it.
// (Exceptions that must exist before JS runs: <title>/meta description in index.html
// and name/description in manifest.webmanifest.)

export const STRINGS = Object.freeze({
  app: {
    name: 'runsesh',
    logoAlt: 'runsesh',
    navLabel: 'Main',
    tabRace: 'Race',
    tabProfile: 'Profile',
    back: 'Back',
    genericError: 'Something went wrong. Please try again.',
    updateAvailable: 'An update is available.',
    updateReload: 'Reload',
  },

  common: {
    notConnectedTitle: 'Not connected yet',
    notConnectedDefault: 'This screen shows mock data. Nothing is saved to an account.',
    comingLater: 'Coming later',
    rank: (n) => `Rank ${n}`,
    ordinal: (n) => {
      const mod100 = n % 100;
      const suffix = mod100 >= 11 && mod100 <= 13 ? 'th' : ({ 1: 'st', 2: 'nd', 3: 'rd' }[n % 10] || 'th');
      return `${n}${suffix}`;
    },
    steps: (n) => `${n} steps`,
  },

  installHint: {
    before: 'Install runsesh: tap ',
    share: 'Share',
    middle: ', then ',
    addToHome: 'Add to Home Screen',
    after: '.',
    dismiss: 'Dismiss',
  },

  race: {
    createParty: 'Create a party',
    partyMembers: (party) => `${party} members`,
    trackLabel: "Today's race track. Swipe sideways to travel along it.",
    trackStart: 'Start',
    trackTick: (k) => `${k}k`,
    runnerLabel: (name, steps) => `${name}: ${steps} steps today`,
    minimapLabel: 'Overview of all runners. Tap a runner to jump to them.',
    you: 'You',
    todayTitle: 'Rankings',
    yourSteps: 'Your steps today',
    leader: 'Leading today',
    behind: (steps, name) => `${steps} behind ${name}`,
    tied: (name) => `Tied with ${name}`,
  },

  competition: {
    banner: 'COMPETITION',
    screenTitle: 'Competition',
    notConnected: 'Competitions are stored on this device only, with mock steps.',
    none: 'No competition yet.',
    create: 'Create a competition',
    mockRulesHint: 'Mock rules for now: per-day modes score finished days only.',
    datesRange: (start, end) => `${start} – ${end}`,
    datesOpen: (start) => `From ${start} (no end date)`,
    statusRunning: 'Running',
    statusNotStarted: 'Not started',
    statusFinished: 'Finished',
    goldenReward: 'Golden reward',
    scoreDaysWon: (n) => `${n} ${n === 1 ? 'day' : 'days'} won`,
    scorePoints: (n) => `${n} pts`,
    scoreSteps: (n) => `${n} steps`,
    showCompetition: 'Show competition',
    pickerLabel: 'Competition',
    mockSuffix: (name) => `${name} (mock)`,
    modes: {
      days_won: 'Days won',
      points_321: 'Points 3-2-1',
      total_steps: 'Total steps',
    },
    form: {
      name: 'Name (optional)',
      namePlaceholder: 'e.g. Autumn Sprint',
      start: 'Start date',
      end: 'End date (optional)',
      endHint: 'Leave empty for an open-ended competition.',
      mode: 'Ranking mode',
      golden: 'Golden reward for the winner',
      submit: 'Create competition',
      created: 'Competition created (local mock only).',
      defaultName: 'Competition',
    },
    errors: {
      nameTooLong: (max) => `Use at most ${max} characters.`,
      startMissing: 'Pick a start date.',
      endInvalid: 'That end date is not valid.',
      endBeforeStart: 'The end date must be on or after the start date.',
      modeMissing: 'Pick a ranking mode.',
      invalid: 'Invalid value.',
      tooMany: (max) => `You can keep up to ${max} local competitions.`,
    },
  },

  profile: {
    customize: 'Customize your avatar',
    yourAvatar: 'Your avatar',
    tapToCustomize: 'Tap to customize',
    customizeButton: 'Customize avatar',
    uploadPhoto: 'Use your own photo as profile picture',
    photoLater: 'Custom profile photos are coming in a later phase.',
    darkTheme: 'Dark theme',
    groupParty: 'PARTY',
    groupSettings: 'SETTINGS',
    partySettings: 'Party settings',
    manageMembers: 'Manage members',
    partyRules: 'Party rules',
    competition: 'Competition',
    login: 'Login / Log out',
    account: 'Account',
    health: 'Health connect',
  },

  avatarEditor: {
    title: 'Your avatar',
    preview: 'Avatar preview',
    skin: 'Skin / body color',
    skinPicker: 'Pick any color',
    swatch: (hex) => `Color ${hex}`,
    tabs: {
      skin: 'Body color',
      hair: 'Hair',
      hairColor: 'Hair color',
      top: 'Tops',
      bottom: 'Bottoms',
      shoes: 'Shoes',
      acc: 'Accessories',
    },
    goldenTitle: 'Golden set',
    goldenHint: 'Locked. Win competitions with a golden reward to unlock.',
    locked: (label) => `${label} (locked)`,
    save: 'Save avatar',
    saved: 'Avatar saved.',
    saveFailed: 'Could not save that avatar.',
  },

  // Labels for avatar part IDs (see js/avatar/parts.js and docs/avatar-schema.md).
  parts: {
    h_none: 'Bald', h_buzz: 'Buzz', h_short: 'Short', h_spiky: 'Spiky', h_long: 'Long',
    h_bob: 'Bob', h_ponytail: 'Ponytail', h_bun: 'Bun', h_curly: 'Curly', h_mohawk: 'Mohawk',
    hc_black: 'Black', hc_brown: 'Brown', hc_auburn: 'Auburn', hc_blonde: 'Blonde',
    hc_grey: 'Grey', hc_blue: 'Blue', hc_pink: 'Pink', hc_green: 'Green',
    t_tee: 'T-shirt', t_tank: 'Tank top', t_jersey: 'Knit sweater', t_hoodie: 'Hoodie',
    t_jacket: 'Jacket', t_singlet: 'Race singlet', t_tracksuit: 'Tracksuit',
    b_shorts: 'Shorts', b_runshorts: 'Running shorts', b_leggings: 'Leggings',
    b_joggers: 'Joggers', b_skirt: 'Skirt',
    s_none: 'Barefoot', s_runner: 'Green runners', s_white: 'White trainers',
    s_blue: 'Blue runners', s_pink: 'Pink runners',
    a_none: 'None', a_cap: 'Cap', a_headband: 'Headband', a_sunglasses: 'Sunglasses',
    a_glasses: 'Glasses', a_headphones: 'Headphones', a_scarf: 'Scarf', a_medal: 'Medal',
    a_watch: 'Sports watch',
    g_glasses: 'Golden glasses', g_vest: 'Golden vest', g_boots: 'Golden boots',
    g_crown: 'Golden crown', g_color: 'Golden color',
  },

  createParty: {
    title: 'Create a party',
    notConnected: 'Parties and invites arrive in a later phase.',
    cardTitle: 'New party',
    name: 'Party name',
    namePlaceholder: 'e.g. Lunch Break Runners',
    invite: 'Invite by email',
    invitePlaceholder: 'friend@example.com',
    submit: 'Create party',
  },

  members: {
    title: 'Manage members',
    admin: (name) => `${name} (admin)`,
    remove: 'Remove',
    invite: 'Invite members',
  },

  rules: {
    title: 'Party rules',
    cardTitle: 'Rules',
    dayResets: 'Day resets at',
    joining: 'Joining',
    inviteOnly: 'Invite only',
    open: 'Open',
    edit: 'Edit rules',
    scoringTitle: 'Step scoring',
    scoringHint: 'Mock setting. It does not change rankings yet.',
    scoring: {
      plain: 'Plain steps',
      elevation_bonus: 'Bonus for steps with elevation gain',
    },
    scoringSaved: 'Step scoring updated (local mock only).',
  },

  login: {
    title: 'Login / Log out',
    notConnected: 'Sign-in will be handled by the auth provider in Phase 2.',
    signIn: 'Sign in',
    email: 'Email',
    continue: 'Continue',
    passkey: 'Sign in with a passkey',
    signedIn: 'Signed in',
    logOut: 'Log out',
    logOutAll: 'Log out of all devices',
  },

  account: {
    title: 'Account',
    cardTitle: 'Your account',
    name: 'Name',
    email: 'Email',
    changePassword: 'Change password',
    dangerZone: 'Danger zone',
    deleteAccount: 'Delete account and data',
  },

  health: {
    title: 'Health connect',
    notConnected: 'Real step data arrives in a later phase. The app currently uses mock steps.',
    intro: 'Three ways to send your steps to runsesh:',
    cards: [
      { title: 'iPhone: Apple Shortcut', text: 'A Shortcut reads your daily step total from Apple Health and sends it to runsesh.', action: 'Set up Shortcut' },
      { title: 'Android: companion app', text: 'A small companion app reads your daily steps from Health Connect and sends them to runsesh.', action: 'Get the app' },
      { title: 'Manual entry', text: 'Type in your step total for a day yourself.', action: 'Enter steps' },
    ],
    privacy: 'Only daily step totals will be shared with your party.',
  },
});
