// Every user-visible string in the app, in one place.
// Plain strings, or small functions for text with values in it.
// (Exceptions that must exist before JS runs: <title>/meta description in index.html
// and name/description in manifest.webmanifest.)

export const STRINGS = Object.freeze({
  app: {
    name: 'runsesh',
    logoAlt: 'runsesh',
    navLabel: 'Main',
    tabRace: 'Race',
    tabCompetition: 'Competition',
    tabProfile: 'Profile',
    back: 'Back',
    genericError: 'Something went wrong. Please try again.',
    updateAvailable: 'An update is available.',
    updateReload: 'Reload',
  },

  common: {
    notConnectedTitle: 'Not connected yet',
    notConnectedDefault: 'This screen shows mock data. Nothing is saved to an account.',
    comingLater: 'Coming later',
    rank: (n) => `Rank ${n}`,
    ordinal: (n) => {
      const mod100 = n % 100;
      const suffix = mod100 >= 11 && mod100 <= 13 ? 'th' : ({ 1: 'st', 2: 'nd', 3: 'rd' }[n % 10] || 'th');
      return `${n}${suffix}`;
    },
    steps: (n) => `${n} steps`,
  },

  installHint: {
    before: 'Install runsesh: tap ',
    share: 'Share',
    middle: ', then ',
    addToHome: 'Add to Home Screen',
    after: '.',
    why: 'It opens full screen like an app.',
    howTo: 'How to install',
    dismiss: 'Dismiss',
  },

  // iPhone / iPad set-up screen (#/profile/iphone)
  iphone: {
    title: 'runsesh on iPhone',
    statusTitle: 'This device',
    statusInstalled: 'Installed: you are using the runsesh app from your Home Screen.',
    statusBrowser: 'Not installed yet: you are using runsesh in the browser.',
    statusOther: 'This is not an iPhone or iPad. These steps are for Apple devices.',
    installTitle: 'Install from Safari',
    installSteps: [
      'Open runsesh in Safari (on iOS 16.4 or later other browsers work too).',
      'Tap the Share button (the square with an arrow pointing up).',
      'Scroll down and tap "Add to Home Screen", then tap "Add".',
      'Open runsesh from the new icon on your Home Screen.',
    ],
    loginTitle: 'Log in once more',
    loginText: 'The installed app keeps its own login, separate from Safari. Log in again inside the app. Password reset links always open in Safari, so finish a reset there, then log in inside the app.',
    stepsTitle: 'Your steps from Apple Health',
    stepsText: 'A web app cannot read Apple Health. An Apple Shortcut on your iPhone reads your daily step total and sends it to runsesh. Set it up below, or enter your steps by hand.',
    manualAction: 'Enter steps by hand',
    // iPhone token (shared token wording is in STRINGS.tokens)
    tokenTitle: 'Your iPhone token',
    tokenIntro: 'The Shortcut uses a personal token instead of your password. It can only send your own daily steps; it cannot read anything or log in.',
    tokenNone: 'You have no iPhone token yet.',
    tokenCreate: 'Create iPhone token',
    // Building the Shortcut
    buildTitle: 'Build the Shortcut',
    buildSteps: [
      'Open the Shortcuts app, tap +, and name the shortcut "runsesh steps".',
      'Add "Find Health Samples": type Steps, Start Date is Today. Add the filter Source is your iPhone (or only your Apple Watch), so steps are not counted twice.',
      'Add "Calculate Statistics": Sum of the Health Samples. Then add "Round Number" to the Ones Place.',
      'Add "Format Date": Current Date, Custom format yyyy-MM-dd.',
      'Add "Get Contents of URL" with the address below. Method POST. Add a Header: Key Authorization, Value = paste the value you copied above (it starts with Bearer). Request Body JSON: day (Text) = Formatted Date, steps (Number) = Rounded Number.',
      'Run it once and allow access to Health. Your steps appear in Health connect.',
      'Automate it: Automation → + → Time of Day (for example 21:00, Daily) → Run Immediately → Run Shortcut "runsesh steps".',
    ],
    urlLabel: 'Address for "Get Contents of URL"',
    limitsNote: 'Up to 20 sends per hour. Only today and the last 3 days can be sent.',
    updateTitle: 'Updates',
    updateText: 'When a new version is ready you will see "An update is available". Tap Reload. If nothing changes, close the app completely and open it again.',
  },

  race: {
    createParty: 'Create a party',
    partyMembers: (party) => `${party} members`,
    trackLabel: "Today's race track. Swipe sideways to travel along it.",
    trackStart: 'Start',
    trackTick: (k) => `${k}k`,
    runnerLabel: (name, steps) => `${name}: ${steps} steps today`,
    minimapLabel: 'Overview of all runners. Tap a runner to jump to them.',
    you: 'You',
    todayTitle: 'Rankings',
    yourSteps: 'Your steps today',
    leader: 'Leading today',
    behind: (steps, name) => `${steps} behind ${name}`,
    tied: (name) => `Tied with ${name}`,
  },

  competition: {
    banner: 'COMPETITION',
    screenTitle: 'Competition settings',
    hubTitle: 'Competition',
    standingsTitle: 'Standings',
    settingsButton: 'Competition settings',
    rulesButton: 'See the rules',
    leaderOnly: (leader) => `Only ${leader} (the party leader) can change these settings.`,
    leaderFallback: 'the leader',
    autoJoin: 'Everyone in the party takes part automatically.',
    // No party / no competition
    noPartyTitle: 'No party yet',
    noPartyText: 'Competitions happen inside a party. Create one or join one with an invite link.',
    emptyTitle: 'No competition yet',
    createOrJoin: 'Create or join a competition',
    leaderEmpty: 'You lead this party: create a competition and everyone takes part.',
    memberEmpty: (leader) => `Waiting for ${leader} to create a competition. You will take part automatically.`,
    create: 'Create a competition',
    none: 'No competition yet.',
    // Theme and photo
    themeTitle: 'Competition theme',
    themeHint: 'Everyone in the party sees the theme you choose.',
    themeSaved: (name) => `Theme: ${name}`,
    themes: {
      circus: 'Classic circus',
      spring: 'Spring',
      summer: 'Summer',
      fall: 'Fall (spooky)',
      winter: 'Winter',
    },
    photoTitle: 'Your own background photo',
    photoHint: 'Optional. Replaces the theme picture for everyone in the party. It is shrunk and its hidden details (like location) are removed before upload.',
    photoUpload: 'Upload a photo',
    photoReplace: 'Replace photo',
    photoRemove: 'Remove photo',
    photoSaved: 'Background photo updated.',
    photoRemoved: 'Background photo removed.',
    photoWorking: 'Uploading…',
    photoErrors: {
      type: 'Choose a JPEG, PNG or WebP image.',
      size: 'That image is too large.',
      decode: 'That file could not be read as an image.',
      upload: 'Could not upload the photo. Try again.',
    },
    // Lifecycle
    endButton: 'End competition now',
    endConfirm: 'End the competition now? Results are frozen and it moves to the calendar.',
    ended: 'Competition ended. See the results in the calendar.',
    deleteButton: 'Delete competition',
    deleteConfirm: 'Delete this competition? It will not appear in the calendar.',
    deleted: 'Competition deleted.',
    saved: 'Competition saved.',
    saveFailed: 'Could not save. Check the fields and try again.',
    actionFailed: 'That did not work. Try again in a moment.',
    notStarted: 'It has not started yet; delete it instead.',
    editTitle: 'Edit competition',
    // Calendar and hall of fame
    calendarTitle: 'Calendar',
    calendarHint: 'Tap a highlighted day to see that competition.',
    prevMonth: 'Previous month',
    nextMonth: 'Next month',
    weekdays: ['Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa', 'Su'],
    dayLabel: (date, name) => (name ? `${date}: ${name}` : date),
    resultsTitle: (name) => `Results: ${name}`,
    liveTitle: (name) => `${name} (running)`,
    noResults: 'No results recorded.',
    hallTitle: 'Hall of Fame',
    hallEmpty: 'No finished competitions yet.',
    hallWinner: (names) => `Winner: ${names}`,
    hallYou: 'Play a competition to appear in the Hall of Fame.',
    hallYourBest: (rank, name) => `Your best: ${rank} in ${name}`,
    someone: 'Former member',
    mockRulesHint: 'Per-day modes score finished days only.',
    datesRange: (start, end) => `${start} – ${end}`,
    datesOpen: (start) => `From ${start} (no end date)`,
    statusRunning: 'Running',
    statusNotStarted: 'Not started',
    statusFinished: 'Finished',
    goldenReward: 'Golden reward',
    scoreDaysWon: (n) => `${n} ${n === 1 ? 'day' : 'days'} won`,
    scorePoints: (n) => `${n} pts`,
    scoreSteps: (n) => `${n} steps`,
    modes: {
      days_won: 'Days won',
      points_321: 'Points 3-2-1',
      total_steps: 'Total steps',
    },
    form: {
      name: 'Name (optional)',
      namePlaceholder: 'e.g. Autumn Sprint',
      start: 'Start date',
      end: 'End date (optional)',
      endHint: 'Leave empty for an open-ended competition (end it later with "End competition now").',
      mode: 'Ranking mode',
      golden: 'Golden reward for the winner',
      submit: 'Create competition',
      save: 'Save changes',
      created: 'Competition created. Everyone in the party takes part.',
      defaultName: 'Competition',
    },
    errors: {
      nameTooLong: (max) => `Use at most ${max} characters.`,
      startMissing: 'Pick a start date.',
      endInvalid: 'That end date is not valid.',
      endBeforeStart: 'The end date must be on or after the start date.',
      modeMissing: 'Pick a ranking mode.',
      invalid: 'Invalid value.',
    },
  },

  profile: {
    customize: 'Customize your avatar',
    yourAvatar: 'Your avatar',
    tapToCustomize: 'Tap to customize',
    customizeButton: 'Customize avatar',
    noName: 'Runner',
    uploadPhoto: 'Use your own photo as profile picture',
    photoLater: 'Custom profile photos are coming in a later phase.',
    darkTheme: 'Dark theme',
    groupParty: 'PARTY',
    groupSettings: 'SETTINGS',
    partySettings: 'Party settings',
    manageMembers: 'Manage members',
    partyRules: 'Party rules',
    competition: 'Competition',
    login: 'Login / Log out',
    account: 'Account',
    health: 'Health connect',
  },

  avatarEditor: {
    title: 'Your avatar',
    preview: 'Avatar preview',
    skin: 'Skin / body color',
    skinPicker: 'Pick any color',
    swatch: (hex) => `Color ${hex}`,
    tabs: {
      skin: 'Body color',
      hair: 'Hair',
      hairColor: 'Hair color',
      top: 'Tops',
      bottom: 'Bottoms',
      shoes: 'Shoes',
      acc: 'Accessories',
    },
    goldenTitle: 'Golden set',
    goldenHint: 'Locked. Win competitions with a golden reward to unlock.',
    locked: (label) => `${label} (locked)`,
    save: 'Save avatar',
    saved: 'Avatar saved.',
    saveFailed: 'Could not save that avatar.',
  },

  // Labels for avatar part IDs (see js/avatar/parts.js and docs/avatar-schema.md).
  parts: {
    h_none: 'Bald', h_buzz: 'Buzz', h_short: 'Short', h_spiky: 'Spiky', h_long: 'Long',
    h_bob: 'Bob', h_ponytail: 'Ponytail', h_bun: 'Bun', h_curly: 'Curly', h_mohawk: 'Mohawk',
    hc_black: 'Black', hc_brown: 'Brown', hc_auburn: 'Auburn', hc_blonde: 'Blonde',
    hc_grey: 'Grey', hc_blue: 'Blue', hc_pink: 'Pink', hc_green: 'Green',
    t_tee: 'T-shirt', t_tank: 'Tank top', t_jersey: 'Knit sweater', t_hoodie: 'Hoodie',
    t_jacket: 'Jacket', t_singlet: 'Race singlet', t_tracksuit: 'Tracksuit',
    b_shorts: 'Shorts', b_runshorts: 'Running shorts', b_leggings: 'Leggings',
    b_joggers: 'Joggers', b_skirt: 'Skirt',
    s_none: 'Barefoot', s_runner: 'Green runners', s_white: 'White trainers',
    s_blue: 'Blue runners', s_pink: 'Pink runners',
    a_none: 'None', a_cap: 'Cap', a_headband: 'Headband', a_sunglasses: 'Sunglasses',
    a_glasses: 'Glasses', a_headphones: 'Headphones', a_scarf: 'Scarf', a_medal: 'Medal',
    a_watch: 'Sports watch',
    g_glasses: 'Golden glasses', g_vest: 'Golden vest', g_boots: 'Golden boots',
    g_crown: 'Golden crown', g_color: 'Golden color',
  },

  createParty: {
    title: 'Create a party',
    cardTitle: 'New party',
    intro: 'You will be the party leader: you invite friends, create competitions and set the rules.',
    name: 'Party name',
    namePlaceholder: 'e.g. Lunch Break Runners',
    nameHint: '2 to 30 characters.',
    nameInvalid: 'Use 2 to 30 characters.',
    submit: 'Create party',
    created: 'Party created. Invite your friends!',
    failed: 'Could not create the party. Try again.',
    alreadyInParty: 'You are already in a party. Leave it first to create a new one.',
  },

  // No party yet, joining with an invite link
  party: {
    noneTitle: 'You are not in a party yet',
    noneText: 'Race your friends: create a party and invite them, or join a friend\'s party with their invite link.',
    create: 'Create a party',
    join: 'Join a party',
    loading: 'Loading your party…',
    loadFailed: 'Could not load your party. Check your connection and try again.',
    retry: 'Try again',
    joinTitle: 'Join a party',
    joinPaste: 'Paste the invite link (or code) a friend sent you.',
    joinField: 'Invite link or code',
    joinCheck: 'Check invite',
    joinPreview: (party, count, leader) => `Join "${party}"? ${count} ${count === 1 ? 'member' : 'members'}${leader ? `, led by ${leader}` : ''}.`,
    joinButton: 'Join party',
    joinCancel: 'Cancel',
    joined: (party) => `Welcome to ${party}!`,
    joinErrors: {
      invalid_invite: 'This invite link is not valid. It may have expired, been used up or been turned off. Ask for a new one.',
      already_in_party: 'You are already in a party. Leave it first to join another one.',
      party_full: 'This party is full (20 members).',
      rate_limited: 'Too many tries. Wait an hour and try again.',
      error: 'Could not join right now. Try again in a moment.',
    },
    inviteButton: 'Invite friends',
  },

  members: {
    title: 'Manage members',
    leader: 'Leader',
    you: (name) => `${name} (you)`,
    unnamed: 'Runner',
    remove: 'Remove',
    removeConfirm: (name) => `Remove ${name} from the party?`,
    removed: (name) => `${name} was removed.`,
    // Invites
    inviteTitle: 'Invite friends',
    inviteText: 'Create a link and send it to a friend. Anyone with the link can join while it works: 7 days, up to 25 people.',
    inviteCreate: 'Create invite link',
    inviteShownOnce: 'Copy or share this link now. For your safety it is shown only once.',
    inviteCopy: 'Copy link',
    inviteShare: 'Share',
    inviteCopied: 'Link copied.',
    inviteCopyFailed: 'Could not copy. Select the link and copy it by hand.',
    inviteDone: 'Done',
    inviteShareText: 'Join my runsesh party!',
    inviteActive: (n) => (n === 0 ? 'You have no working invite links.' : `You have ${n} working invite ${n === 1 ? 'link' : 'links'}.`),
    inviteRevokeMine: 'Turn off my invite links',
    inviteRevokeMineConfirm: 'Turn off all invite links you created? People who already joined stay in the party.',
    inviteRevokedMine: (n) => `${n} ${n === 1 ? 'link' : 'links'} turned off.`,
    inviteExpireAll: 'Expire all invite links',
    inviteExpireAllConfirm: 'Expire every current invite link of the party (yours and everyone else\'s)? Members stay.',
    inviteExpiredAll: (n) => `${n} ${n === 1 ? 'link' : 'links'} expired.`,
    inviteTooMany: 'You have too many working links. Turn some off first.',
    // Leaving
    leaveTitle: 'Leave the party',
    leaveText: 'You can join or create another party afterwards.',
    leaveLeaderText: (next) => (next ? `You are the leader. If you leave, ${next} becomes the new leader.` : 'You are the only member: leaving deletes the party.'),
    leave: 'Leave party',
    leaveConfirm: 'Leave this party?',
    left: 'You left the party.',
    failed: 'That did not work. Try again in a moment.',
  },

  rules: {
    title: 'Party rules',
    cardTitle: 'Rules',
    nameTitle: 'Party name',
    rename: 'Save name',
    renamed: 'Party name saved.',
    dayResets: 'Day resets at',
    dayResetsValue: 'Midnight (each member\'s local time)',
    joining: 'Joining',
    joiningValue: 'Invite link only (max 20 members)',
    scoringTitle: 'Step scoring',
    scoringHint: 'Elevation data is not available from Health Connect or the web app, so the bonus is coming later.',
    scoring: {
      plain: 'Plain steps',
      elevation_bonus: 'Bonus for steps with elevation gain (coming later)',
    },
    scoringSaved: 'Step scoring updated.',
    failed: 'Could not save. Try again.',
  },

  login: {
    title: 'Login / Log out',
    signedInAs: (email) => `Signed in as ${email}`,
    logOut: 'Log out',
    logOutAll: 'Log out of all devices',
    logOutAllHint: 'Ends your session on every phone and computer.',
  },

  // Sign-up, login, password reset. Messages never reveal whether an email has an account.
  auth: {
    notConfigured: 'runsesh is not connected to its server yet. (Developer: fill in js/config.js.)',
    tagline: 'Step competitions with your party.',
    loginTitle: 'Log in',
    signupTitle: 'Create an account',
    forgotTitle: 'Forgot password',
    resetTitle: 'Set a new password',
    email: 'Email',
    password: 'Password',
    newPassword: 'New password',
    displayName: 'Display name',
    displayNameHint: '2 to 30 characters. Your party sees this name.',
    passwordHint: (min) => `At least ${min} characters. Long passphrases are great; password managers welcome.`,
    logIn: 'Log in',
    signUp: 'Create account',
    sendReset: 'Send reset link',
    savePassword: 'Save new password',
    toSignup: 'New here? Create an account',
    toLogin: 'Already have an account? Log in',
    toForgot: 'Forgot your password?',
    privacyLink: 'Privacy policy',
    privacyAgree: 'By creating an account you agree to the privacy policy.',
    working: 'Please wait…',
    // Generic results
    loginFailed: 'Could not log in. Check your email and password, and make sure you confirmed your email.',
    signupDone: 'Check your email. If you can create an account with this address, we sent you a confirmation link. After confirming, return to the app and log in.',
    signupFailed: 'Could not create the account. Check your details and try again in a moment.',
    resetSent: 'If an account exists for this email, we have sent a link to reset your password.',
    resetDone: 'Your password was changed. Other devices were logged out.',
    resetFailed: 'Could not change the password. The link may have expired; request a new one.',
    resetNeedsLink: 'Open the reset link from your email to set a new password.',
    // Field errors
    emailInvalid: 'Enter a valid email address.',
    passwordShort: (min) => `Use at least ${min} characters.`,
    passwordLong: 'That password is too long (max 72 bytes).',
    nameInvalid: 'Use 2 to 30 characters.',
  },

  // auth-callback.html (opened from email links, usually in the phone's browser)
  callback: {
    working: 'Checking your link…',
    confirmed: 'Email confirmed. After confirming, return to the app and log in.',
    confirmedElsewhere: 'If this was a sign-up link, your email is confirmed: return to the app and log in. If it was a password reset, open the link in the same browser where you asked for it, or request a new one.',
    invalid: 'This link is invalid or has expired. Request a new one from the app.',
    openApp: 'Open runsesh',
  },

  account: {
    title: 'Account',
    cardTitle: 'Your account',
    name: 'Display name',
    email: 'Email',
    noName: 'Not set yet',
    editName: 'Change display name',
    saveName: 'Save name',
    nameSaved: 'Display name saved.',
    nameFailed: 'Could not save the name. Use 2 to 30 characters.',
    changePassword: 'Change password',
    savePassword: 'Save new password',
    passwordChanged: 'Password changed. Other devices were logged out.',
    passwordFailed: 'Could not change the password. Try again.',
    sessionTitle: 'Sessions',
    dangerZone: 'Delete account',
    deleteAccount: 'Delete account and data',
    deleteLater: 'Account deletion is coming soon. Until then, ask us through the contact in the privacy policy.',
    privacyLink: 'Privacy policy',
  },

  tokens: {
    loading: 'Loading…',
    status: (hint, created) => `Token ending in …${hint}, created ${created}.`,
    lastReceived: (when) => `Last received ${when}.`,
    neverReceived: 'Nothing received yet.',
    revoke: 'Revoke',
    revokeConfirm: 'Revoke this token? The phone using it stops sending steps.',
    revoked: 'Token revoked.',
    limit: 'You already have 2 tokens. Revoke one to create another.',
    shownOnce: 'Copy this now and paste it into your phone. It is shown only once; runsesh does not keep it. Do not share it.',
    headerValueLabel: 'Value for the Authorization header',
    copy: 'Copy',
    copied: 'Copied.',
    copyFailed: 'Could not copy. Select the text and copy it by hand.',
    done: 'Done',
    failed: 'Could not reach the server. Try again in a moment.',
    copyUrl: 'Copy address',
    urlCopied: 'Address copied.',
  },

  health: {
    title: 'Health connect',
    intro: 'Ways to send your daily steps to runsesh:',
    androidTitle: 'Android: Health Connect',
    androidText: 'A free open-source app on your Android phone reads your daily step total from Health Connect and sends it to runsesh. A browser cannot read Health Connect, so the app is needed.',
    androidAction: 'Connect my Android phone',
    // Android set-up section
    androidSectionTitle: 'Connect your Android phone',
    androidIntro: (app) => `runsesh does not make this app. ${app} is an independent open-source app (MIT licence) that sends data from Health Connect to an address you choose. runsesh only reads the daily step totals it sends.`,
    androidDoOnPhone: 'Do these steps on your Android phone, with runsesh open in the phone\'s browser, so you can copy and paste.',
    androidInstallTitle: '1. Install the app',
    androidInstallSteps: (app, version, nameOnPhone) => [
      `Open the ${app} release page below and download app-release.apk (version ${version}).`,
      'Open the downloaded file. Android asks once to allow installs from your browser; allow it, then tap Install.',
      `Open "${nameOnPhone}". Answer its setup questions: pick Health Connect, and "Decide later" for the data types. You add the webhook in step 3.`,
    ],
    androidReleaseLink: 'Release page on GitHub',
    androidTokenTitle: '2. Your Android token',
    androidTokenIntro: 'The app uses a personal token instead of your password. It can only send your own daily steps; it cannot read anything or log in.',
    androidTokenNone: 'You have no Android token yet.',
    androidTokenCreate: 'Create Android token',
    androidSetupTitle: '3. Set up the app',
    androidUrlLabel: 'Webhook address',
    androidSetupSteps: [
      'Health tab → Data Types: switch on only Steps. Switch everything else off.',
      'Tap Grant and allow only Steps in Health Connect, including reading in the background.',
      'Health tab → Data Resolution: set Steps to hourly. This keeps every sync small enough for runsesh.',
      'Health tab → Webhook: add the webhook address above.',
      'Webhook Headers: add a header with name Authorization and, as value, paste the value you copied in step 2 (it starts with Bearer).',
      'Advanced: keep "Daily totals in payload" on. Keep "Record metadata in payload" and diagnostics off. Never switch on "Allow plain HTTP webhooks".',
      'Sync Schedule: every 15 to 60 minutes.',
      'Android Settings → Apps → Life Dashboard → Battery: choose Unrestricted (or switch off battery optimisation), otherwise Android may stop background syncs.',
      'Tap Test ping, then Save Changes, then Sync Now. "Last received" in step 2 shows when runsesh got data.',
    ],
    androidLimitsNote: 'Up to 20 sends per hour. Only today and the last 3 days are saved, so do not use Backfill. Only the daily step totals are kept; everything else the app sends is ignored.',
    shortcutTitle: 'iPhone: Apple Shortcut',
    shortcutText: 'An Apple Shortcut reads your daily step total from Apple Health and sends it to runsesh.',
    shortcutAction: 'Set up on iPhone',
    manualTitle: 'Manual entry',
    manualText: "Type in today's step total.",
    manualLabel: "Today's steps",
    manualSave: 'Save steps',
    manualSaved: 'Steps saved.',
    manualInvalid: 'Enter a whole number from 0 to 100,000.',
    manualFailed: 'Could not save your steps. Try again.',
    historyTitle: 'Your last 7 days',
    historyEmpty: 'No steps saved yet.',
    historyFailed: 'Could not load your history.',
    sources: { manual: 'manual', health_connect: 'Health Connect', shortcut: 'Shortcut', admin: 'added by admin' },
    privacy: 'Only daily step totals are saved. Steps are self-reported.',
    privacyLink: 'Privacy policy',
  },
});
